### ISSUE TITLE
two questions for  "CLUE Emotion Analysis"

### ISSUE THREAD

**Issue by CoderBinGe** [zhedongzheng/tensorflow-nlp#14]
Hi, I have two questions to ask you:

1. `text = ['[CLS]'] + text + ['[SEP]']` , here, why does text not tokenize? like this,`text = ['[CLS]'] + tokenizer.tokenize(text) + ['[SEP]'] `
2. For BertFinetune, `x = x[1]` , here, why x = x[1]?

**Comment by zhedongzheng** [comment]
Hi, 
1. The tokenization of Chinese is different from English
The tokenization of Chinese is just splitting characters (unlike english)
```
  text = list(text)
  text = ['[CLS]'] + text + ['[SEP]']
```
For example, if the input text is "欢迎来北京",
It will become a list [ '[CLS]',  '欢', '迎', '来', '北', '京', '[SEP]' ]

```tokenizer.tokenize(text)``` is for English, which is to split sentence by subwords (more complex)

2. BertFinetune will return more than one elements.
x[0] is the whole encoded sequence (with full timesteps)
x[1] is the pooled output (no timestep)
Since it is a classification task, we just use the pooled output x[1]
If it is a sequence tagging task, we need to use x[0]

**Comment by CoderBinGe** [comment]
OK, Thank you very much! I still have a lot to learn!
